from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
import uuid
import datetime

@dataclass
class Artifact:
    """Represents a file or object generated by the agent."""
    name: str
    content: str
    type: str  # e.g., 'code', 'document', 'diagram'
    path: Optional[str] = None # Suggested path

@dataclass
class AgentTask:
    """Represents a task given to the agent."""
    type: str # e.g., 'ontology_generation', 'code_generation'
    description: str
    context: Dict[str, Any] = field(default_factory=dict)
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    created_at: datetime.datetime = field(default_factory=datetime.datetime.now)
    tenant_id: Optional[str] = None

@dataclass
class AgentResponse:
    """Represents the outcome of an agent's work."""
    status: str # 'success', 'failed'
    message: str
    artifacts: List[Artifact] = field(default_factory=list)
