# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import semantic_engine_pb2 as semantic__engine__pb2


class SemanticEngineStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.IngestTriples = channel.unary_unary(
        '/semantic_engine.SemanticEngine/IngestTriples',
        request_serializer=semantic__engine__pb2.IngestRequest.SerializeToString,
        response_deserializer=semantic__engine__pb2.IngestResponse.FromString,
        )
    self.IngestFile = channel.unary_unary(
        '/semantic_engine.SemanticEngine/IngestFile',
        request_serializer=semantic__engine__pb2.IngestFileRequest.SerializeToString,
        response_deserializer=semantic__engine__pb2.IngestResponse.FromString,
        )
    self.GetNeighbors = channel.unary_unary(
        '/semantic_engine.SemanticEngine/GetNeighbors',
        request_serializer=semantic__engine__pb2.NodeRequest.SerializeToString,
        response_deserializer=semantic__engine__pb2.NeighborResponse.FromString,
        )
    self.Search = channel.unary_unary(
        '/semantic_engine.SemanticEngine/Search',
        request_serializer=semantic__engine__pb2.SearchRequest.SerializeToString,
        response_deserializer=semantic__engine__pb2.SearchResponse.FromString,
        )
    self.ResolveId = channel.unary_unary(
        '/semantic_engine.SemanticEngine/ResolveId',
        request_serializer=semantic__engine__pb2.ResolveRequest.SerializeToString,
        response_deserializer=semantic__engine__pb2.ResolveResponse.FromString,
        )
    self.GetAllTriples = channel.unary_unary(
        '/semantic_engine.SemanticEngine/GetAllTriples',
        request_serializer=semantic__engine__pb2.EmptyRequest.SerializeToString,
        response_deserializer=semantic__engine__pb2.TriplesResponse.FromString,
        )
    self.QuerySparql = channel.unary_unary(
        '/semantic_engine.SemanticEngine/QuerySparql',
        request_serializer=semantic__engine__pb2.SparqlRequest.SerializeToString,
        response_deserializer=semantic__engine__pb2.SparqlResponse.FromString,
        )
    self.DeleteNamespaceData = channel.unary_unary(
        '/semantic_engine.SemanticEngine/DeleteNamespaceData',
        request_serializer=semantic__engine__pb2.EmptyRequest.SerializeToString,
        response_deserializer=semantic__engine__pb2.DeleteResponse.FromString,
        )
    self.HybridSearch = channel.unary_unary(
        '/semantic_engine.SemanticEngine/HybridSearch',
        request_serializer=semantic__engine__pb2.HybridSearchRequest.SerializeToString,
        response_deserializer=semantic__engine__pb2.SearchResponse.FromString,
        )
    self.ApplyReasoning = channel.unary_unary(
        '/semantic_engine.SemanticEngine/ApplyReasoning',
        request_serializer=semantic__engine__pb2.ReasoningRequest.SerializeToString,
        response_deserializer=semantic__engine__pb2.ReasoningResponse.FromString,
        )


class SemanticEngineServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def IngestTriples(self, request, context):
    """Ingests a batch of triples
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IngestFile(self, request, context):
    """Ingests a file (CSV, Markdown)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNeighbors(self, request, context):
    """Queries the graph (Basic traversal for now)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Search(self, request, context):
    """Vector Search (Placeholder for hybrid query)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResolveId(self, request, context):
    """Resolves a string URI to a Node ID
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllTriples(self, request, context):
    """Get all stored triples (for graph visualization)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def QuerySparql(self, request, context):
    """Executes a SPARQL query
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteNamespaceData(self, request, context):
    """Deletes all data associated with a namespace
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HybridSearch(self, request, context):
    """Hybrid search combining vector similarity and graph traversal
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ApplyReasoning(self, request, context):
    """Applies automated reasoning to a namespace
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SemanticEngineServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'IngestTriples': grpc.unary_unary_rpc_method_handler(
          servicer.IngestTriples,
          request_deserializer=semantic__engine__pb2.IngestRequest.FromString,
          response_serializer=semantic__engine__pb2.IngestResponse.SerializeToString,
      ),
      'IngestFile': grpc.unary_unary_rpc_method_handler(
          servicer.IngestFile,
          request_deserializer=semantic__engine__pb2.IngestFileRequest.FromString,
          response_serializer=semantic__engine__pb2.IngestResponse.SerializeToString,
      ),
      'GetNeighbors': grpc.unary_unary_rpc_method_handler(
          servicer.GetNeighbors,
          request_deserializer=semantic__engine__pb2.NodeRequest.FromString,
          response_serializer=semantic__engine__pb2.NeighborResponse.SerializeToString,
      ),
      'Search': grpc.unary_unary_rpc_method_handler(
          servicer.Search,
          request_deserializer=semantic__engine__pb2.SearchRequest.FromString,
          response_serializer=semantic__engine__pb2.SearchResponse.SerializeToString,
      ),
      'ResolveId': grpc.unary_unary_rpc_method_handler(
          servicer.ResolveId,
          request_deserializer=semantic__engine__pb2.ResolveRequest.FromString,
          response_serializer=semantic__engine__pb2.ResolveResponse.SerializeToString,
      ),
      'GetAllTriples': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllTriples,
          request_deserializer=semantic__engine__pb2.EmptyRequest.FromString,
          response_serializer=semantic__engine__pb2.TriplesResponse.SerializeToString,
      ),
      'QuerySparql': grpc.unary_unary_rpc_method_handler(
          servicer.QuerySparql,
          request_deserializer=semantic__engine__pb2.SparqlRequest.FromString,
          response_serializer=semantic__engine__pb2.SparqlResponse.SerializeToString,
      ),
      'DeleteNamespaceData': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteNamespaceData,
          request_deserializer=semantic__engine__pb2.EmptyRequest.FromString,
          response_serializer=semantic__engine__pb2.DeleteResponse.SerializeToString,
      ),
      'HybridSearch': grpc.unary_unary_rpc_method_handler(
          servicer.HybridSearch,
          request_deserializer=semantic__engine__pb2.HybridSearchRequest.FromString,
          response_serializer=semantic__engine__pb2.SearchResponse.SerializeToString,
      ),
      'ApplyReasoning': grpc.unary_unary_rpc_method_handler(
          servicer.ApplyReasoning,
          request_deserializer=semantic__engine__pb2.ReasoningRequest.FromString,
          response_serializer=semantic__engine__pb2.ReasoningResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'semantic_engine.SemanticEngine', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
