# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import semantic_engine_pb2 as semantic__engine__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in semantic_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SemanticEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestTriples = channel.unary_unary(
                '/semantic_engine.SemanticEngine/IngestTriples',
                request_serializer=semantic__engine__pb2.IngestRequest.SerializeToString,
                response_deserializer=semantic__engine__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.GetNeighbors = channel.unary_unary(
                '/semantic_engine.SemanticEngine/GetNeighbors',
                request_serializer=semantic__engine__pb2.NodeRequest.SerializeToString,
                response_deserializer=semantic__engine__pb2.NeighborResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/semantic_engine.SemanticEngine/Search',
                request_serializer=semantic__engine__pb2.SearchRequest.SerializeToString,
                response_deserializer=semantic__engine__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.ResolveId = channel.unary_unary(
                '/semantic_engine.SemanticEngine/ResolveId',
                request_serializer=semantic__engine__pb2.ResolveRequest.SerializeToString,
                response_deserializer=semantic__engine__pb2.ResolveResponse.FromString,
                _registered_method=True)
        self.GetAllTriples = channel.unary_unary(
                '/semantic_engine.SemanticEngine/GetAllTriples',
                request_serializer=semantic__engine__pb2.EmptyRequest.SerializeToString,
                response_deserializer=semantic__engine__pb2.TriplesResponse.FromString,
                _registered_method=True)
        self.DeleteTenantData = channel.unary_unary(
                '/semantic_engine.SemanticEngine/DeleteTenantData',
                request_serializer=semantic__engine__pb2.EmptyRequest.SerializeToString,
                response_deserializer=semantic__engine__pb2.DeleteResponse.FromString,
                _registered_method=True)


class SemanticEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IngestTriples(self, request, context):
        """Ingests a batch of triples
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNeighbors(self, request, context):
        """Queries the graph (Basic traversal for now)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Vector Search (Placeholder for hybrid query)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveId(self, request, context):
        """Resolves a string URI to a Node ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllTriples(self, request, context):
        """Get all stored triples (for graph visualization)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTenantData(self, request, context):
        """Deletes all data associated with a tenant
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SemanticEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestTriples': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestTriples,
                    request_deserializer=semantic__engine__pb2.IngestRequest.FromString,
                    response_serializer=semantic__engine__pb2.IngestResponse.SerializeToString,
            ),
            'GetNeighbors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNeighbors,
                    request_deserializer=semantic__engine__pb2.NodeRequest.FromString,
                    response_serializer=semantic__engine__pb2.NeighborResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=semantic__engine__pb2.SearchRequest.FromString,
                    response_serializer=semantic__engine__pb2.SearchResponse.SerializeToString,
            ),
            'ResolveId': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveId,
                    request_deserializer=semantic__engine__pb2.ResolveRequest.FromString,
                    response_serializer=semantic__engine__pb2.ResolveResponse.SerializeToString,
            ),
            'GetAllTriples': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllTriples,
                    request_deserializer=semantic__engine__pb2.EmptyRequest.FromString,
                    response_serializer=semantic__engine__pb2.TriplesResponse.SerializeToString,
            ),
            'DeleteTenantData': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTenantData,
                    request_deserializer=semantic__engine__pb2.EmptyRequest.FromString,
                    response_serializer=semantic__engine__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'semantic_engine.SemanticEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('semantic_engine.SemanticEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SemanticEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestTriples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic_engine.SemanticEngine/IngestTriples',
            semantic__engine__pb2.IngestRequest.SerializeToString,
            semantic__engine__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNeighbors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic_engine.SemanticEngine/GetNeighbors',
            semantic__engine__pb2.NodeRequest.SerializeToString,
            semantic__engine__pb2.NeighborResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic_engine.SemanticEngine/Search',
            semantic__engine__pb2.SearchRequest.SerializeToString,
            semantic__engine__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic_engine.SemanticEngine/ResolveId',
            semantic__engine__pb2.ResolveRequest.SerializeToString,
            semantic__engine__pb2.ResolveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllTriples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic_engine.SemanticEngine/GetAllTriples',
            semantic__engine__pb2.EmptyRequest.SerializeToString,
            semantic__engine__pb2.TriplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTenantData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/semantic_engine.SemanticEngine/DeleteTenantData',
            semantic__engine__pb2.EmptyRequest.SerializeToString,
            semantic__engine__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
